# Generated by Django 6.0.7 on 2026-07-10 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('voided', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('eft', 'EFT'), ('other', 'Other')], max_length=10)),
                ('voided', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_vat_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('sell_percent_default', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardStockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=3)),
                ('market_ref', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=10)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_lines', to='pobusa.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('card', 'Card stock'), ('sealed', 'Sealed stock'), ('general', 'General inventory')], max_length=10)),
                ('source_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pobusa.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SealedStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sealed_lines', to='pobusa.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pobusa.store'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pobusa.store'),
        ),
        migrations.CreateModel(
            name='GeneralInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cooldrinks', 'Cooldrinks'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_items', to='pobusa.store')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pdf_file', models.FileField(upload_to='pobusa_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='pobusa.store')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='pobusa.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='pobusa.store')),
            ],
        ),
        migrations.CreateModel(
            name='BuyPercentTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_tiers', to='pobusa.store')),
            ],
            options={
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='AccountingExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_account_code', models.CharField(max_length=50)),
                ('cogs_account_code', models.CharField(max_length=50)),
                ('vat_account_code', models.CharField(max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('export_format', models.CharField(choices=[('pastel', 'Sage Pastel'), ('sage', 'Sage Business Cloud'), ('xero', 'Xero'), ('generic', 'Generic')], default='generic', max_length=10)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='pobusa.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Store owner'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='pobusa.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pobusa_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_buy_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sell_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='pobusa.store')),
            ],
            options={
                'unique_together': {('store', 'date')},
            },
        ),
    ]
