# Generated by Django 6.0.4 on 2026-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstockline',
            name='card_set',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cardstockline',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
