# Generated by Django 6.0.4 on 2026-07-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0003_invoice_discount_amount_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstockline',
            name='variant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
