# Generated by Django 6.0.4 on 2026-07-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0004_cardstockline_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tcgcsv_category_id', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=60, unique=True)),
                ('product_type', models.CharField(choices=[('single', 'Single card'), ('sealed', 'Sealed product'), ('accessory', 'Accessory')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('set_name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pobusa.game')),
            ],
        ),
        migrations.CreateModel(
            name='TCGCSVSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcgcsv_category_id', models.PositiveIntegerField()),
                ('tcgcsv_group_id', models.PositiveIntegerField()),
                ('tcgcsv_product_id', models.PositiveIntegerField(unique=True)),
                ('tcgcsv_group_name', models.CharField(blank=True, max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tcgcsv_source', to='pobusa.catalogproduct')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['product_type', 'game'], name='pobusa_cata_product_327c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['name'], name='pobusa_cata_name_1e52c7_idx'),
        ),
    ]
