# Generated by Django 5.2.17 on 2026-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0007_tcgcsvsource_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['game', 'release_date'], name='pobusa_cata_game_id_9d6f2c_idx'),
        ),
    ]
