# Generated by Django 5.2.17 on 2026-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0008_catalogproduct_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
