# Generated by Django 5.2.17 on 2026-08-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0009_catalogproduct_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('single', 'Single card'), ('sealed', 'Sealed product'), ('accessory', 'Accessory')], max_length=10)),
                ('sub_category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(editable=False, max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='pobusa.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product_type'], name='pobusa_stor_store_i_8b44c3_idx')],
            },
        ),
    ]
