# Generated by Django 5.2.17 on 2026-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0010_storecustomproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
