# Generated by Django 5.2.17 on 2026-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0011_catalogproduct_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
