# Generated by Django 5.2.17 on 2026-08-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobusa', '0012_catalogproduct_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCatalogStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_stock', to='pobusa.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'sku'], name='pobusa_clie_store_i_029792_idx')],
                'unique_together': {('store', 'sku')},
            },
        ),
    ]
